# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packet.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, "", "packet.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cpacket.proto"\xa4\x01\n\x08Settings\x12\x11\n\tfrequency\x18\x01 \x01(\x02\x12\r\n\x05power\x18\x02 \x01(\x05\x12\x11\n\tbandwidth\x18\x03 \x01(\x02\x12\x18\n\x10spreading_factor\x18\x04 \x01(\x05\x12\x13\n\x0b\x63oding_rate\x18\x05 \x01(\x05\x12\x10\n\x08preamble\x18\x06 \x01(\x05\x12\x0f\n\x07set_crc\x18\x07 \x01(\x08\x12\x11\n\tsync_word\x18\x08 \x01(\r"\x1f\n\x0cTransmission\x12\x0f\n\x07payload\x18\x01 \x01(\x0c">\n\x03Gps\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x12\n\nsatellites\x18\x03 \x01(\r"r\n\x03Log\x12\x11\n\tcrc_error\x18\x01 \x01(\x08\x12\x15\n\rgeneral_error\x18\x02 \x01(\x08\x12\x11\n\x03gps\x18\x03 \x01(\x0b\x32\x04.Gps\x12\x10\n\x08rssi_avg\x18\x04 \x01(\x02\x12\x0b\n\x03snr\x18\x05 \x01(\x02\x12\x0f\n\x07payload\x18\x06 \x01(\x0c"U\n\x07Request\x12\x0e\n\x06search\x18\x01 \x01(\x08\x12\x10\n\x08settings\x18\x02 \x01(\x08\x12\x0b\n\x03gps\x18\x03 \x01(\x08\x12\x1b\n\x0bstateChange\x18\x04 \x01(\x0e\x32\x06.State"\xb3\x01\n\x06Packet\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.PacketType\x12\x1b\n\x08settings\x18\x02 \x01(\x0b\x32\t.Settings\x12#\n\x0ctransmission\x18\x03 \x01(\x0b\x32\r.Transmission\x12\x11\n\x03log\x18\x04 \x01(\x0b\x32\x04.Log\x12\x19\n\x07request\x18\x05 \x01(\x0b\x32\x08.Request\x12\x11\n\x03gps\x18\x06 \x01(\x0b\x32\x04.Gps\x12\x0b\n\x03\x61\x63k\x18\x07 \x01(\x08*e\n\nPacketType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08SETTINGS\x10\x01\x12\x10\n\x0cTRANSMISSION\x10\x02\x12\x07\n\x03LOG\x10\x03\x12\x0b\n\x07REQUEST\x10\x04\x12\x07\n\x03GPS\x10\x05\x12\x07\n\x03\x41\x43K\x10\x06*3\n\x05State\x12\x0b\n\x07STANDBY\x10\x00\x12\x0f\n\x0bTRANSMITTER\x10\x01\x12\x0c\n\x08RECEIVER\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "packet_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PACKETTYPE"]._serialized_start = 665
    _globals["_PACKETTYPE"]._serialized_end = 766
    _globals["_STATE"]._serialized_start = 768
    _globals["_STATE"]._serialized_end = 819
    _globals["_SETTINGS"]._serialized_start = 17
    _globals["_SETTINGS"]._serialized_end = 181
    _globals["_TRANSMISSION"]._serialized_start = 183
    _globals["_TRANSMISSION"]._serialized_end = 214
    _globals["_GPS"]._serialized_start = 216
    _globals["_GPS"]._serialized_end = 278
    _globals["_LOG"]._serialized_start = 280
    _globals["_LOG"]._serialized_end = 394
    _globals["_REQUEST"]._serialized_start = 396
    _globals["_REQUEST"]._serialized_end = 481
    _globals["_PACKET"]._serialized_start = 484
    _globals["_PACKET"]._serialized_end = 663
# @@protoc_insertion_point(module_scope)
